# Generated by Django 5.2.10 on 2026-01-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='SBI-Clerk', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
